// Placeholder power_pstates_pkg (will be auto-generated by extract_power_table.py)
package power_pstates_pkg;
  typedef struct packed {
    logic [15:0] volt_mV;
    logic [15:0] freq_MHz;
    logic [31:0] dyn_coeff_mw_per_util;
    logic [31:0] leak_coeff_mw;
  } power_pstate_t;
  localparam int NUM_PSTATES = 5;
  localparam power_pstate_t PSTATES [NUM_PSTATES] = '{
    '{16'd950,16'd1200,32'd1000,32'd300},
    '{16'd900,16'd1000,32'd800, 32'd250},
    '{16'd800,16'd800, 32'd600, 32'd200},
    '{16'd700,16'd600, 32'd420, 32'd150},
    '{16'd650,16'd400, 32'd300, 32'd120}
  };
endpackage : power_pstates_pkg
