name: NeuraEdge NPU CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y yosys verilator python3-pip git
          # Try to install SymbiYosys - if it fails, we'll skip formal checks
          pip3 install --user symbiyosys || echo "SymbiYosys installation failed, formal checks will be skipped"
          # Add pip user bin to PATH
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Run Basic Linting
        run: make lint

      - name: Run Basic Compilation
        run: make compile

      - name: Run System Linting
        run: make lint_system

      - name: Run System Compilation
        run: make compile_system

      - name: Run System Synthesis
        run: make synth_system

      - name: Run System Formal Checks
        run: make formal_system
        continue-on-error: true  # Allow this step to fail without breaking the workflow
