name: PE RTL CI

on:
  pull_request:
    paths:
      - 'rtl/pe/**'
      - 'rtl/common/regfile.sv'
      - 'rtl/common/sram_bank.v'
      - 'Makefile'

jobs:
  pe-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y verilator
      - name: Lint PE RTL
        run: make lint_pe
      - name: Compile PE RTL
        run: make compile_pe
      - name: Run PE Smoke Tests
        run: make test_pe_smoke
